name: Compilability check
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      NDK_VER: r17
      NDK_PLAT: linux
    strategy:
      matrix:
        abi: [ "armeabi-v7a", "arm64-v8a", "x86" ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Setup the environment
        run: |
          sudo pip3 install meson==0.58.2
          sudo apt-get install nasm ninja-build

      - name: Executing the script
        run: |
          echo ANDROID_HOME=$ANDROID_HOME
          echo ANDROID_NDK_LATEST_HOME=$ANDROID_NDK_LATEST_HOME
          wget -q -O android-ndk-${NDK_VER}-${NDK_PLAT}-x86_64.zip https://dl.google.com/android/repository/android-ndk-${NDK_VER}-${NDK_PLAT}-x86_64.zip
          unzip -q android-ndk-${NDK_VER}-${NDK_PLAT}-x86_64.zip
          export ANDROID_SDK_HOME=$ANDROID_HOME
          export ANDROID_NDK_HOME=`pwd`/android-ndk-${NDK_VER}
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/${NDK_PLAT}-x86_64/bin:$ANDROID_NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/${NDK_PLAT}-x86_64/bin:$PATH
          ./ffmpeg-android-maker.sh -all-free -all-gpl -android=21 -abis=${{ matrix.abi }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./output
          name: ffmpeg-android-4.4.1
